# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pointable < Formula
  desc "The code-generator used to get the pointer to scalar literals in Go"
  homepage "https://github.com/ebi-yade/pointable#readme"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ebi-yade/pointable/releases/download/v1.0.2/pointable_1.0.2_darwin_amd64.tar.gz"
      sha256 "10097c841ca673e2581fe974291411fcbc5635f04424a146a17a4340675f60e7"

      def install
        bin.install "pointable"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ebi-yade/pointable/releases/download/v1.0.2/pointable_1.0.2_darwin_arm64.tar.gz"
      sha256 "14fdb3850946d66fd4f37a8fab8e562bb19013d0426ab5eb67dd204e0c17be43"

      def install
        bin.install "pointable"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ebi-yade/pointable/releases/download/v1.0.2/pointable_1.0.2_linux_amd64.tar.gz"
      sha256 "a207aa441b4f47b304bb36b7d77c02216399bccf02675c9ac34b9917b8c2058a"

      def install
        bin.install "pointable"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ebi-yade/pointable/releases/download/v1.0.2/pointable_1.0.2_linux_arm64.tar.gz"
      sha256 "a7c247a64d165d3f8c5faaeba63f9f86cc2c5c76150a7d8233794c8a65ea08eb"

      def install
        bin.install "pointable"
      end
    end
  end

  test do
    system "#{bin}/pointable -version"
  end
end
